#!/usr/bin/env bash
# Installs and configures Nginx to include a custom X-Served-By header

apt-get update -y
apt-get install -y nginx

HOSTNAME_VALUE=$(hostname)

cat <<EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html;

    server_name _;

    add_header X-Served-By $HOSTNAME_VALUE;

    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOF

systemctl restart nginx
