#!/usr/bin/env bash
# Installs and configures Nginx to include a custom X-Served-By header

# Install nginx
apt-get update -y
apt-get install -y nginx

# Get machine hostname
HOSTNAME_VALUE=$(hostname)

# Replace default nginx config
cat <<EOF > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm;

    server_name _;

    add_header X-Served-By $HOSTNAME_VALUE;

    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOF

# Restart nginx
systemctl restart nginx
