#!/usr/bin/env bash
# Installs Nginx with the following configurations:
# - Listens on port 80
# - Returns a page containing "Holberton School" at /
# - Redirects /redirect_me with a 301 status code
# - Custom 404 page displaying "Ceci n'est pas une page"

apt-get update
apt-get install -y nginx

mkdir -p /var/www/html

echo "Holberton School" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html;

    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    error_page 404 /404.html;
    location = /404.html {
        root /var/www/html;
        internal;
    }
}
" > /etc/nginx/sites-available/default

service nginx restart
